== Modellbeschreibung

Gestaltungspläne gemäss Art. 24 PBG sind Teil der Nutzungsplanung und damit wie der Zonenplan
und das Baureglement eigentümerverbindlich. Der Gestaltungsplan verfeinert die Vorgaben der
(Rahmen-)Nutzungsplanung mit zusätzlichen Aussagen über die Nutzung, Erschliessung, Bebauung
und Ausstattung. +

Die Sonderbestimmungen der im ÖREB-Kataster dargestellten Gestaltungspläne werden in der Regel
auf einem oder mehreren (Detail-)Plänen sowie in Vorschriften festgehalten. Im Gegensatz zum
Zonenplan werden die Inhalte der Gestaltungspläne nicht vollständig geometrisch erfasst, sondern –
wie im Geodatenmodell Bereich Nutzungsplanung des Bundes bereits beschrieben – nur der
Planungsperimeter. Die weiteren Planinhalte sind über die im ÖREB-Kataster hinterlegten PDF-Dateien des jeweiligen Gestaltungsplanes zugänglich. Der Perimeter der einzelnen Gestaltungspläne
wird als überlagernder Nutzungsplaninhalt (andere flächenbezogene Festlegungen) erfasst und die
dazugehörigen Dokumente (Plan und Sonderbauvorschriften) im PDF-Format über einen
Dokumentlink mit der entsprechenden Geometrie verknüpft.

=== Zonentypen
[cols="1,1,3,5"]
|=======
h|Code h| Abkürzung h| Bezeichnung h| Beschreibung
3+| *6 andere flächenbezogene Festlegungen* |
| 61 | | Bereiche rechtsgültiger Sondernutzungspläne | Bereiche rechtsgültiger Sondernutzungspläne umfassen Gebiete mit Sonderbauvorschriften. Sie ergänzen, überlagern oder verändern Festlegungen des Rahmennutzungsplanes.
| 61.1 | rGP | _Bereich rechtsgültiger Gestaltungsplan_ + 
[small]_Hinweis: +
Die Bezeichnung wird im konkreten Fall auf den Namen des Gestaltungsplans gesetzt._ | Diese Bereiche umfassen Gebiete mit Sonderbauvorschriften. Sie ergänzen, überlagern oder verändern Festlegungen des Zonenplans.
| 61.9 | wrSP | Bereich weiterer rechtsgültiger Sondernutzungsplan | Diese Bereiche umfassen weitere Gebiete mit Sonderbauvorschriften. Sie ergänzen, überlagern oder verändern Festlegungen des Zonenplans, sind aber nicht als Bereich rechtsgültiger Gestaltungsplan zu betrachten.
|=======


*Ergänzende Information zur Definition des Zonentyps "Bereich rechtsgültiger Gestaltungsplan"* +

Dokumente und Rechtssätze können nur mit Zonentypen und nicht mit einzelnen Geometrien
verknüpft werden. Deshalb braucht es für jeden rechtsgültigen Gestaltungsplan einen eigenen
Zonentyp. Der Code für diesen setzt sich zusammen aus dem kantonalen Typ "61.1" und einer
eindeutigen, laufenden Nummer innerhalb der Gemeinde (z. B. "1", der Code lautet dann z. B.
61.1.1). + 

Die Abkürzung ist stets "rGP". Die Bezeichnung soll anstelle von "Bereich rechtsgültiger
Gestaltungsplan" den Namen des Gestaltungsplans enthalten, vgl. Beispiele in nachfolgender Liste. +

Beispiele für die Definition von Bereichen rechtsgültiger Gestaltungspläne:

[cols="1,1,3"]
|=======
h| Code h| Abkürzung h| Bezeichnung
| 61.1.1 | rGP | Gestaltungsplan "Dörfli"
| 61.1.2 | rGP | Gestaltungsplan "Freihof"
| ... | ... | ...
| 61.1.11 | rGP | Gestaltungsplan "Freihof West"
|=======

ifdef::backend-pdf[]
<<<
endif::[]